### ISSUE TITLE
Sometimes can't disable keycast-mode

### ISSUE THREAD

**Issue by timlod** [tarsius/keycast#16]
Hi,

Thanks for this package, it's great for presenting/live coding in front of an audience!

I noticed that sometimes I am unable to disable keycast-mode. What happens is that the mode is disabled, but the actual keycasting is just frozen on the last command. I'm not 100% sure yet how to isolate this problem, but I have a hunch that it may be related to a lost display connection - I run an emacs daemon, and when there is a hiccup with the connection I may have to reconnect to the `emacsclient` (after which keycast-mode is stuck and I need to restart emacs). 

I will update this issue once I'm sure exactly what the problem is/how to reproduce.

**Comment by benthamite** [comment]
@timlod Did you manage to diagnose the issue? I'm also having this problem.

**Comment by timlod** [comment]
Hey, I've been quite busy and have not presented since I noticed this last time :/

**Comment by danrobi11** [comment]
Same here. Now my mode-line is empty. keycast broke my mode line

**Comment by tarsius** [comment]
Try

```diff
@@ -282,7 +282,7 @@ (define-minor-mode keycast-mode
               (t
                (setcdr cons (cons 'mode-line-keycast (cdr cons)))))
         (add-hook 'pre-command-hook 'keycast--update t))
-    (let ((cons (memq 'mode-line-keycast mode-line-format)))
+    (let ((cons (keycast--tree-member 'mode-line-keycast mode-line-format)))
       (cond (keycast--removed-tail
              (setcar cons (car keycast--removed-tail))
              (setcdr cons (cdr keycast--removed-tail)))
```

And if you change the value of `keycast-remove-tail-elements`, then make sure you do that before enabling the mode.

**Comment by tarsius** [comment]
@danrobi11 Does the :heart: mean "that fixed it for me" or "thanks for looking at this"?

**Comment by danrobi11** [comment]
@tarsius 

> Does the heart mean "that fixed it for me" or "thanks for looking at this"?

It was for looking at it while I had time to test in a virtualbox.

I confirm with new code keycast-mode enable/disbale does work as intended.

Thank you much for the support, very appreciated.

**Comment by danrobi11** [comment]
Since I have you around @tarsius 
Is it possible to keep the mode-line info (date/time, modes) while having keycast enabled ? I've tried hard to find `how-to` but does not seems to be an option to enable that, right ? 
Non-technical user here :/

**Comment by danrobi11** [comment]
> (setq keycast-remove-tail-elements nil)

@tarsius Fantastic! Thanks again.
