### ISSUE TITLE
Error: "Cannot turn on keycast-mode"

### ISSUE THREAD

**Issue by AtomicNess123** [tarsius/keycast#17]
I try to enable keycast mode. However I am getting this error:

`helm-M-x-execute-command: Cannot turn on keycast-mode.  mode-line-buffer-identification not found in mode-line-format.  Try customizing keycast-insert-after.`

**Comment by tarsius** [comment]
Notice the last part of that error:

>Try customizing keycast-insert-after

**Comment by AtomicNess123** [comment]
Sorry for the ignorance, newbie here. Which value shall I choose?

**Comment by tarsius** [comment]
I don't know. Check the value of `mode-line-format`, which should be a list. Pick one of the elements and use that as the value of ` keycast-insert-after`. Once that works you can decide on where you actually want the keycast information to appear and what element corresponds to that location and then use that as the value of `keycast-insert-after`.
