### ISSUE TITLE
keycast stops working after `password-reading`

### ISSUE THREAD

**Issue by whatacold** [tarsius/keycast#20]
Hi,

I noticed that keycast will stop working after evaluating `(password-read "Password prompt: ")`,
but it can be worked around by doing `M-x keycast-mode` twice.

The version I installed is 20210616.826 .

**Comment by tarsius** [comment]
It disables itself while the password is being read but afterwards it resumes its work.

The implementation of this is very simple:

```elisp
(defvar keycast--reading-passwd nil)

(defun keycast--format (format)
  (and (not keycast--reading-passwd)
       ...here the usual work happens...))

(defun keycast--read-passwd (fn prompt &optional confirm default)
  (let ((keycast--reading-passwd t))
    (funcall fn prompt confirm default)))

(advice-add 'read-passwd :around #'keycast--read-passwd
```

So I don't see how keycast could permanently stop showing the used bindings.

What Emacs version are you using?

**Comment by tarsius** [comment]
And now I am watching your video. :smile: 

Love how you mispronounce "world". I also cannot pronounce that world correctly but it cracked me up how very differently we get it wrong. :stuck_out_tongue_winking_eye: 

And I guess I have go give some feedback. I liked the video; the speed was good and you covered some details that other videos with similar scope fail to mention.

**Comment by whatacold** [comment]
> It disables itself while the password is being read but afterwards it resumes its work.
> 
> The implementation of this is very simple:

Yeah, I've checked ab41be43b6d9efd5eff5ad7f22a997cc41e8daf0 , and found that it's simple, but it doesn't work anymore after `password-read` finishes.

I noticed this when screencasting the Magit video a few days ago. So I just worked around it by disabling and enabling the mode again, and then cut it off from the video as I was in a rush, and today I took time to reproduce it and confirmed that it didn't work, at least on my box.

BTW, it really blew my mind that the code is so concise that I can't believe it has only <200 lines of code.😲

Thank you for another great package!❤️

**Comment by whatacold** [comment]
> Love how you mispronounce "world". I also cannot pronounce that world correctly but it cracked me up how very differently we get it wrong. stuck_out_tongue_winking_eye

🤔Hmm, I didn't notice that I mispronounce "world", thanks for pointing it out, and I am going to watch it again to see I can find out how I mispronounced :) .
Actually, I mispronounce many more, and I hope I can correct them through the practice I make in this channel :)

> And I guess I have go give some feedback. I liked the video; the speed was good and you covered some details that other videos with similar scope fail to mention.

Thank you and thanks for such a great package. Any kinds of feedback are very welcome. 😁

I hope this video can help more people to take a look at Magit and get started with it, and then they can dive deeper themselves and find more surprise from Magit.

**Comment by whatacold** [comment]
> ...
> and today I took time to reproduce it and confirmed that it didn't work, at least on my box.

I will also try to find out why it fails on my side.

**Comment by whatacold** [comment]
Well, this problem occurs when `keycast-log-mode` is enabled,

A minimal recipe (`/tmp/keycast-debug.el`) to reproduce it:
```elisp
(load-file "/path/to/keycast/keycast.el")

(setq debug-on-message "wrong-type")
(toggle-debug-on-error)

;(keycast-mode)
(keycast-log-mode)

(push '(self-insert-command nil nil) keycast-substitute-alist)
```

Start Emacs with `emacs -Q -l /tmp/keycast-debug.el`, then:
1. Type some commands to let keycast pop up the frame, e.g. `M-p`
2. Eval `(read-passwd "password: ")`, or execute a command, e.g. `C-x b *Message*`
   Then there is an error shows in the `*Message*` buffer: `Error in pre-command-hook (keycast--update): (wrong-type-argument char-or-string-p nil)`

It seems to be related to input in minibuffer, and I try to find out where this error comes from with edebug, but failed.

**Comment by whatacold** [comment]
Thanks for the fix, I just confirmed that it works after `read-passwd`.

But there is still `wrong-type-argument` errors when, for example, switching buffers, as I mentioned before.

Can it be reproduced on your side?

**Comment by tarsius** [comment]
> But there is still `wrong-type-argument` errors when, for example, switching buffers, as I mentioned before.

Not sure what previous mention you are referring to. Please give me new steps to reproduce.

**Comment by whatacold** [comment]
`/tmp/keycast-debug.el`:

```
(load-file "/path/to/keycast/keycast.el")

(setq debug-on-message "wrong-type")
(toggle-debug-on-error)

;(keycast-mode)
(keycast-log-mode)

(push '(self-insert-command nil nil) keycast-substitute-alist)
```

1. Emacs with `emacs -Q -l /tmp/keycast-debug.el`,
1. Type some commands to let keycast pop up the frame, e.g. `M-p`,
2. Switch to buffer `*Messages*` by `C-x b *Messages*`, and there will be an error while typing the first `*`.

   `Error in pre-command-hook (keycast--update): (wrong-type-argument char-or-string-p nil)`

**Comment by tarsius** [comment]
> (push '(self-insert-command nil nil) keycast-substitute-alist)

Aarrr, another feature I didn't think of when I eventually added `keycast-log-mode`. (I think most people, myself included, only use `keycast-mode`.) On the plus side, I wrote the password hiding in a way that did not cause it to fail (i.e., leak secrets) due to such bugs.

**Comment by whatacold** [comment]
Now it works like a charm ❤️
