### ISSUE TITLE
Consider supporting header-line

### ISSUE THREAD

**Issue by t-e-r-m** [tarsius/keycast#23]
Hi, keycast only supports the mode-line right now.  But it is also possible to use the header-line in place of the mode line.

Example: https://github.com/rougier/nano-modeline

(Otherwise, one can set `header-line-format` to `mode-line-format` (with other necessary changes) and turn on `global-hide-mode-line-mode` to get the "mode line" at the top of the window.)

It is not possible to use keycast when the `global-hide-mode-line-mode` and the `header-line` is active.  Support for the header-line with a flag to specify the same would be super.

**Comment by tarsius** [comment]
It's likely that I will do that eventually but it's also likely that I won't do it soon.

**Comment by tarsius** [comment]
I've implemented support for that now.

**Comment by t-e-r-m** [comment]
Thank you!
