### ISSUE TITLE
How kill keycast-log-mode buffer? 

### ISSUE THREAD

**Issue by arstum** [tarsius/keycast#27]
How disable keycast-log-mode.
I can't kill the keycast new buffer that the frame I run keycast-log-mode.

**Comment by tarsius** [comment]
It should now be possible to kill that buffer as usual.

**Comment by arstum** [comment]
How to do it?

**Comment by tarsius** [comment]
1. Quit `keycast-log-mode`. (Without doing that first, it wouldn't make sense to kill the buffer anyway; it would instantly be recreated.)
2. Go to the buffer and kill it, e.g., using `M-x kill-buffer`.

The thing that wasn't possible before my change above, is to go to the log frame/buffer. The frame is explicitly configure to not be selectable. Now, when the mode is exited, then that restriction is removed.

**Comment by arstum** [comment]
![2023-11-01-134331_1920x1080_scrot](https://github.com/tarsius/keycast/assets/14139978/85894da6-f37a-4754-9943-c7db6fbba80a)
No name in the buffer list.

**Comment by tarsius** [comment]
The name of the buffer is ` *keycast*` (note the space at the beginning). Such buffers are not listed as completion candidates by commands that act on buffers. This isn't a defect, it is a feature that allows omitting certain buffers *by default*. To list those buffers, all you have to do is type a space at the beginning of your input, when you are being prompted for a buffer.

**Comment by arstum** [comment]
*keycast* buffer name  inexistent.

**Comment by tarsius** [comment]
Try `(setq keycast-log-buffer-name "nospace")`.

**Comment by arstum** [comment]
can kill the buffer name "nospace",but the frame can not be killed.

**Comment by tarsius** [comment]
You can make this frame behave more like other frames by removing entries from `keycast-log-frame-alist`. You probably want to start by removing `(minibuffer . nil)` but might have to remove other things as well. You can learn more about this at https://www.gnu.org/software/emacs/manual/html_node/emacs/Frame-Parameters.html.
