### ISSUE TITLE
when keycast-insert-after is nil, don't add keycast to modeline.

### ISSUE THREAD

**Issue by mohkale** [tarsius/keycast#9]
I'm trying to integrate keycast with spaceline, and to do so I'm creating a spaceline segment for keycast. Problem is keycast-mode won't activate unless I set `keycast-insert-after` to something... which I don't see any point in doing so because spacelines just going to override it anyways.

So I propose enable the mode, assign the hooks and just don't add to the mode line if the user hasn't specified a location to add it to.

**Comment by mohkale** [comment]
I'd also appreciate an optional argument for `keycast-mode-line-update` which prevents it from updating the mode-line by itself.

**Comment by mohkale** [comment]
See also [193](https://github.com/TheBB/spaceline/issues/193)

**Comment by tarsius** [comment]
> I'd also appreciate an optional argument for `keycast-mode-line-update` which prevents it from updating the mode-line by itself.

What is that good for?

**Comment by tarsius** [comment]
It appears `minions-mode` has gone through some additional iterations that are missing from `keycast-mode` (use `magit-log-trace-definition` on the former).

It might be a while until I get back to this. Meanwhile, please verify that `minions` already works as expected without any further changes.

**Comment by mohkale** [comment]
oh, sorry for the miscommunication, I'm not implementing minions support (honestly no idea what minions even does). The lost comment in the issue mentions adding keycast support and there wasn't a dedicated issue for keycast so I referenced it instead.

> What is that good for -- after all updating is its purpose. Maybe you should just copy-paste this function and adjust the copy to your needs.

Maybe abstract it out into two functions? `keycast-update` to update `keycast--this-command` and `keycast-mode-line-update` to call `keycast-update` and then `force-mode-line-update`.

**Comment by tarsius** [comment]
> Maybe abstract it out into two functions?

Well maybe. Still interested in learning why, though.

**Comment by mohkale** [comment]
Spaceline updates the mode-line itself, I just didn't want two calls to update-modeline to take place out of sync. If you feel this is too needy then feel free to ignore that. It's not a huge issue, though could come in useful if any other packages want to build on keycast somewhere down the line.

I'd still appreciate keycast working even when `keycast-insert-after` is nil.

**Comment by tarsius** [comment]
> Spaceline updates the mode-line itself,

By calling `force-mode-line-update`? That only *schedules* an update. If something else also does so "within the same command", then that should not make a difference and only one update should happen. (Assuming I got that right of course.)

**Comment by tarsius** [comment]
See https://github.com/tarsius/keycast/issues/10#issuecomment-582067346.
